  version: "3.8"
  services:
    db:
      image: postgres:15
      environment:
        POSTGRES_DB: taskflow
        POSTGRES_USER: taskflow
        POSTGRES_PASSWORD: devpass
      ports:
        - "5432:5432"
      volumes:
        - dbdata:/var/lib/postgresql/data
    api:
      build: .
      ports:
        - "5000:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__Default=Host=db;Database=taskflow;Username=taskflow;Password=devpass
      depends_on:
        - db
  volumes:
    dbdata: