services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Secret=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpiryMinutes=${JWT_EXPIRY_MINUTES}
      - Jwt__RefreshExpiryMinutes=${JWT_REFRESH_EXPIRY_MINUTES}
      - EmailOptions__SmtpHost=${SMTP_HOST}
      - EmailOptions__SmtpPort=${SMTP_PORT}
      - EmailOptions__SmtpUser=${SMTP_USER}
      - EmailOptions__SmtpPass=${SMTP_PASS}
      - EmailOptions__From=${SMTP_FROM}
      - EmailOptions__EnableSsl=${SMTP_ENABLE_SSL}
    depends_on:
      - db

volumes:
  dbdata: